import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>BOMer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen">
        <div className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700 mb-0">
          BOMer
        </div>
        <div className="text-1xl md:text-2xl font-bold text-gray-600 mt-0">
          Simple Bill of Materials 
        </div>
        <div className="pt-5">
          <Link href={'/sales'}>Sales </Link> |
          <Link href={'/products'}>Products </Link> |
          <Link href={'/materials'}>Materials </Link> |
          <Link href={'/suppliers'}>Suppliers </Link> 
        </div>
      </main>
    </>
  );
};


export default Home;
